### PR TITLE
Done Task 2

### PR DESCRIPTION
**Pull request by starboi02**
__6__ 

#### Short description of what this resolves:

Added screenshot.

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-
starboi02

### CODE REVIEW

**Comment by starboi02** [comment]
@achintagrawal please review

**Comment by achintagrawal** [comment]
@starboi02 did you make it by yourself or just copied it from someone else? there is only one layer in layer panel.

**Comment by starboi02** [comment]
Yes,sir I made it myself.There's only one layer as I merged the layers.

**Comment by achintagrawal** [comment]
@starboi02  ok

**Pull request merged**
